"use client";

import { useEffect, useMemo, useState } from "react";
import { BookRow, Data, project, records } from "./projection";
import s from "./workspace.module.css";

const money = (value: unknown) => Number(value || 0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const date = (value: string) => value ? new Date(value+"T12:00:00").toLocaleDateString("en-US") : "";
const businessMenu = [["profile","BP","Business Profile"],["import","QI","QuickBooks Import"],["customers","CU","Customers"],["products","PS","Products & Services"],["editor","EI","Estimate / Invoice Editor"],["reports","IR","Invoice Reports"],["documents","DO","Documents"],["communications","ES","Email & SMS"]];
const cashMenu = [["timeline","CF","Cashflow Planner"],["setup","SP","Setup / Paychecks"],["transaction","TX","Add Transaction"],["rules","RR","Recurring Rules"],["cards","CC","CC Snapshots"],["archives","AR","Archives"]];
const readonly = "Read-only online copy";
function Disabled({children}:{children:React.ReactNode}) { return <button disabled title={readonly}>{children}</button>; }
function Field({name,value,multiline=false}:{name:string;value?:unknown;multiline?:boolean}) {
  return <label className={multiline?s.full:undefined}>{name}{multiline ? <textarea value={String(value??"")} readOnly rows={3}/> : <input value={String(value??"")} readOnly/>}</label>;
}
function Check({name,value}:{name:string;value:unknown}) { return <label className={s.check}><input type="checkbox" checked={Boolean(Number(value))} disabled/>{name}</label>; }
function Status({value}:{value:unknown}) { const text=String(value || "planned"); return <span className={`${s.badge} ${text==='paid'?s.paid:text==='reconciled'?s.reconciled:''}`}>{text==='planned'?'Pay':text}</span>; }

export default function Workspace({rows,isOwner,busy,error,syncedAt,refresh,signOut}:{rows:BookRow[];isOwner:boolean;busy:boolean;error:string;syncedAt:string|null;refresh:()=>void;signOut:()=>void}) {
  const [mode,setMode]=useState("business");
  const [page,setPage]=useState("profile");
  const [theme,setTheme]=useState("dark");
  const [collapsed,setCollapsed]=useState(false);
  const [search,setSearch]=useState("");
  const [filter,setFilter]=useState("all");
  const [chosen,setChosen]=useState<Data|null>(null);
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
  const [calc,setCalc]=useState(false);
  const [expression,setExpression]=useState("");
  const [calcNotice,setCalcNotice]=useState("");
  useEffect(()=>{setTheme(localStorage.getItem("sbooksTheme")||"dark");setCollapsed(localStorage.getItem("sbooksOnlineMenuCollapsed")==="1");},[]);
  const projection=useMemo(()=>project(rows),[rows]);
  const customers=records(rows,"customers"), products=records(rows,"products"), documents=records(rows,"documents");
  const profile=records(rows,"business_profile")[0]||{};
  const customer=(id:unknown)=>customers.find(c=>c.id===id)?.name||"";
  function navigate(key:string) {setPage(key);setChosen(null);setSearch("");}
  function switchMode() {const next=mode==='business'?'cashflow':'business';setMode(next);navigate(next==='business'?'profile':'timeline');}
  function jump(value:string) {setMonth(value);const target=projection.periods.find(p=>p.start_date.slice(0,7)===value)||projection.periods.find(p=>p.start_date.slice(0,7)>value);if(target)document.getElementById(`online-period-${target.start_date}`)?.scrollIntoView({block:'start',behavior:'smooth'});}
  function selectDocument(doc:Data) {setChosen(doc);setPage('editor');}
  const list=documents.filter(d=>(filter==='all'||d.type===filter)&&`${d.number} ${customer(d.customer_id)}`.toLowerCase().includes(search.toLowerCase()));
  const report=documents.filter(d=>d.type==='invoice'&&String(d.issue_date).startsWith(month));
  const totals=(docs:Data[],field:string)=>docs.reduce((sum,d)=>sum+Number(d[field]||0),0);
  function exportReport() {
    const quote=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';
    const csv=[['Number','Customer','Issue date','Subtotal','Tax','Total','Received'],...report.map(d=>[d.number,customer(d.customer_id),d.issue_date,d.subtotal,d.tax_amount,d.total,d.amount_paid])].map(row=>row.map(quote).join(',')).join('\r\n');
    const href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=href;a.download=`invoices-${month}.csv`;a.click();URL.revokeObjectURL(href);
  }
  function documentTable(docs:Data[]) {return <div className={s.tableWrap}><table><thead><tr><th>Type</th><th>Number</th><th>Customer</th><th>Issue date</th><th>Status</th><th>Total</th><th>Received</th><th>Balance due</th><th>Actions</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.type}</td><td>{d.number}</td><td>{customer(d.customer_id)}</td><td>{d.issue_date}</td><td><Status value={d.status}/></td><td>{money(d.total)}</td><td>{money(d.amount_paid)}</td><td>{money(Math.max(0,Number(d.total)-Number(d.amount_paid||0)))}</td><td><button onClick={()=>selectDocument(d)}>Open</button></td></tr>)}</tbody></table>{!docs.length&&<p>No documents found.</p>}</div>;}
  function lane(account:Data|undefined,title:string) {return <div className={s.lane}><h3>{title}</h3>{account?.days.map((day:Data)=><div className={s.day} key={day.date}><div className={s.dayline}><span>{date(day.date)}</span><span>Bal: <b>{money(day.balance)}</b></span></div>{day.items.length?day.items.map((item:Data)=><div className={s.item} key={item.id}><span className={s.description} title={item.description}><Status value={item.status}/> {item.description}</span><span className={Number(item.amount)<0?s.negative:s.positive}>{money(item.amount)}</span><Disabled>Edit</Disabled></div>):<span className={s.muted}>-</span>}</div>)}</div>;}
  function cards(data:Data,title:string) {return <div className={s.lane}><h3>{title}</h3><Disabled>Edit balances (this paycheck)</Disabled><div className={s.day}>{data.cards.map((card:Data)=><div className={s.item} key={card.name}><span className={s.description} title={card.name}>{card.name} {card.due_day&&<span className={s.badge}>{card.due_day}</span>} <Status value={card.pay_status}/></span><span className={s.positive}>{money(card.balance)}</span><Disabled>Edit</Disabled></div>)}<div className={s.totalRow}><b>Total {title.startsWith('Business')?'Biz ':''}CC</b><b className={s.negative}>{money(data.total)}</b></div><Disabled>Create {title.startsWith('Business')?'cc-biz':'CC'} payment</Disabled></div></div>;}
  function renderBusiness() {
    if(page==='profile')return <section className={s.panel}><h2>Business Profile</h2><div className={s.form3}><Field name="Company name" value={profile.company_name}/><Field name="Company phone" value={profile.company_phone}/><Field name="Company email" value={profile.company_email}/><Field name="Company website" value={profile.company_website}/><Field name="Estimate prefix" value={profile.estimate_prefix}/><Field name="Invoice prefix" value={profile.invoice_prefix}/><Field name="Company address" value={profile.company_address} multiline/><Field name="Default tax rate (%)" value={profile.default_tax_rate}/><Field name="Default terms" value={profile.default_terms} multiline/><Disabled>Save Business Profile</Disabled></div></section>;
    if(page==='customers'||page==='products'){
      const isCustomer=page==='customers', data=chosen||{};
      const source=(isCustomer?customers:products).filter(r=>`${r.name} ${r.email||r.sku||''}`.toLowerCase().includes(search.toLowerCase()));
      return <section className={s.panel}><h2>{isCustomer?'Customers':'Products & Services'}</h2><div className={s.form2}><Field name="Name" value={data.name}/><Field name={isCustomer?'Contact name':'SKU / code'} value={isCustomer?data.contact_name:data.sku}/>{isCustomer?<><Field name="Email" value={data.email}/><Field name="Phone" value={data.phone}/><Field name="Billing address" value={data.billing_address} multiline/><Field name="Notes" value={data.notes} multiline/></>:<><Field name="Description" value={data.description} multiline/><Field name="Default unit price" value={data.default_unit_price}/><Check name="Taxable" value={data.taxable}/></>}<Check name={isCustomer?'Active customer':'Active product'} value={data.is_active}/><div className={`${s.actions} ${s.full}`}><Disabled>Save {isCustomer?'Customer':'Product'}</Disabled><button onClick={()=>setChosen(null)}>Clear</button></div></div><div className={s.toolbar}><input aria-label="Search" placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className={s.tableWrap}><table><thead><tr><th>Name</th><th>{isCustomer?'Email':'SKU'}</th><th>{isCustomer?'Phone':'Unit price'}</th><th>Actions</th></tr></thead><tbody>{source.map(r=><tr key={r.id}><td>{r.name}</td><td>{isCustomer?r.email:r.sku}</td><td>{isCustomer?r.phone:money(r.default_unit_price)}</td><td><button onClick={()=>setChosen(r)}>Open</button> <Disabled>Delete</Disabled></td></tr>)}</tbody></table></div></section>;
    }
    if(page==='editor'){
      const d=chosen||{}, lines=records(rows,'document_lines').filter(l=>l.document_id===d.id).sort((a,b)=>a.sort_order-b.sort_order);
      return <section className={s.panel}><div className={s.toolbar}><h2>Estimate / Invoice Editor</h2><select aria-label="Choose document" value={d.id||''} onChange={e=>setChosen(documents.find(x=>String(x.id)===e.target.value)||null)}><option value="">Choose document</option>{documents.map(x=><option key={x.id} value={x.id}>{x.number} - {customer(x.customer_id)}</option>)}</select></div><div className={s.form3}><Field name="Type" value={d.type}/><Field name="Number" value={d.number}/><Field name="Customer" value={customer(d.customer_id)}/><Field name="Issue date" value={d.issue_date}/><Field name="Due date" value={d.due_date}/><Field name="Status" value={d.status}/><Field name="Tax rate (%)" value={d.tax_rate}/><Field name="Payments received" value={d.amount_paid}/><Field name="Notes" value={d.notes} multiline/><Field name="Terms" value={d.terms} multiline/><b className={s.full}>Customer acceptance</b><Check name="Enable customer acceptance page for this estimate" value={d.acceptance_enabled}/><b className={s.full}>Payment options</b>{[['accept_manual_ach','Manual ACH / bank transfer'],['accept_stripe_card','Stripe cards'],['accept_stripe_ach','Stripe ACH debit'],['accept_paypal','PayPal'],['accept_venmo','Venmo'],['use_full_portal','Use full customer portal']].map(([key,text])=><Check key={key} name={text} value={d[key]}/>)}</div><div className={s.toolbar}><h3>Line Items</h3><Disabled>Add Line</Disabled></div>{lines.map(l=><div className={s.lineItem} key={l.id}><Field name="Product" value={products.find(p=>p.id===l.product_id)?.name||'Manual item'}/><Field name="Description" value={l.description} multiline/><Field name="Quantity" value={l.quantity}/><Field name="Unit price" value={l.unit_price}/><Check name="Taxable" value={l.taxable}/><Disabled>Remove</Disabled></div>)}<div className={s.totals}>{[['Subtotal',d.subtotal],['Tax',d.tax_amount],['Total',d.total],['Received',d.amount_paid],['Balance Due',Math.max(0,Number(d.total||0)-Number(d.amount_paid||0))]].map(([name,value])=><div key={name}><span>{name}</span><b>{money(value)}</b></div>)}</div><div className={s.actions}><Disabled>Save Document</Disabled><button onClick={()=>setChosen(null)}>Clear</button></div></section>;
    }
    if(page==='documents')return <section className={s.panel}><div className={s.toolbar}><h2>Documents</h2><div className={s.actions}>{['all','estimate','invoice'].map(f=><button aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)}>{f==='all'?'All':f==='estimate'?'Estimates':'Invoices'}</button>)}</div><input aria-label="Search documents" placeholder="Search documents" value={search} onChange={e=>setSearch(e.target.value)}/></div>{documentTable(list)}</section>;
    if(page==='reports')return <section className={s.panel}><h2>Invoice Reports</h2><div className={s.toolbar}><label>Report month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button onClick={exportReport}>Download CSV</button></div><div className={s.totals}>{[['Pre-tax sales','subtotal'],['Tax','tax_amount'],['Total','total'],['Received','amount_paid']].map(([name,field])=><div key={field}><span>{name}</span><b>{money(totals(report,field))}</b></div>)}</div>{documentTable(report)}</section>;
    if(page==='import')return <section className={s.panel}><h2>QuickBooks Import</h2><fieldset disabled className={s.form2}>{['QuickBooks backup ZIP','Customers export','Products/services export','Invoices export'].map(name=><label key={name}>{name}<input type="file"/></label>)}<Disabled>Preview Import</Disabled><Disabled>Commit Import</Disabled></fieldset></section>;
    return <section className={s.panel}><h2>Email &amp; SMS</h2><div className={s.form2}><Field name="Recipient"/><Field name="Subject"/><Field name="Message" multiline/><Disabled>Send Email</Disabled><Disabled>Send SMS</Disabled></div><h3>Sent Documents</h3>{documentTable(documents.filter(d=>d.last_sent_at))}</section>;
  }
  function renderCashflow() {
    if(page==='timeline')return <><section className={s.panel}><div className={s.rule}><b>Rule: Due day 1-15 = "1st-of-month" bills. Due day 16-EOM = "mid-month" bills.</b><span>Funding: 1-15 funded by previous month's last paycheck; 16-EOM funded by current month's first paycheck.</span></div></section><div className={s.toolbar}><h1>Cashflow Planner</h1><span className={s.muted}>Anchor payday: {projection.settings?.anchor_date||'-'} - Horizon: {projection.settings?.horizon_days||365} days</span></div>{!projection.settings?<p>Waiting for planner settings to sync.</p>:!projection.periods.length?<p>No pay periods available.</p>:projection.periods.map(p=><section className={s.period} id={`online-period-${p.start_date}`} key={p.start_date}><div className={s.payday}><b>Payday - {date(p.paycheck.date)} - {money(p.paycheck.amount)}</b></div><div className={s.periodHeader}><div><b>{date(p.start_date)} - {date(p.end_date)}</b><div className={s.muted}>Payday: {p.paycheck.date} - Paycheck: {money(p.paycheck.amount)}</div></div><div><span className={s.badge}>{p.three_paycheck_month?'3-paycheck month':'Pay period'}</span><br/><Disabled>Archive</Disabled></div></div><div className={s.balances}>{p.accounts.map((a:Data)=><div className={s.balance} key={a.account_id}><div>{a.account_name}</div><b>{money(a.end_balance)}</b><small>Start {money(a.start_balance)} - End {money(a.end_balance)}</small></div>)}</div><div className={s.lanes}>{lane(p.accounts.find((a:Data)=>a.account_id===1)||p.accounts[0],'Personal Bills (Checking)')}{cards(p.cc,'Credit Cards (Snapshot)')}{lane(p.accounts.find((a:Data)=>a.account_id===2)||p.accounts[1],'Business Bills (Checking)')}{cards(p.cc_biz,'Business CC (Snapshot)')}</div></section>)}</>;
    const entity=page==='setup'?'paychecks':page==='rules'?'recurring_rules':page==='cards'?'cc_snapshots':page==='archives'?'pay_period_archives':'transactions';
    const columns:Record<string,string[]>={paychecks:['date','account_id','amount'],recurring_rules:['description','cadence','amount','start_date'],cc_snapshots:['name','snapshot_date','side','balance','pay_status'],pay_period_archives:['start_date','archived_at'],transactions:['effective_date','description','amount','status']};
    return <section className={s.panel}><h2>{cashMenu.find(m=>m[0]===page)?.[2]}</h2>{page==='setup'&&<div className={s.form3}><Field name="Anchor date" value={projection.settings?.anchor_date}/><Field name="Horizon days" value={projection.settings?.horizon_days}/><Disabled>Save Setup</Disabled></div>}{page==='transaction'&&<div className={s.form2}><Field name="Description"/><Field name="Amount"/><Field name="Effective date"/><Disabled>Save Transaction</Disabled></div>}<div className={s.tableWrap}><table><thead><tr>{columns[entity].map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{records(rows,entity).map((r,i)=><tr key={i}>{columns[entity].map(k=><td key={k}>{['amount','balance'].includes(k)?money(r[k]):String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></section>;
  }
  function calculate() {try {if(!/^[\d.\s+*/()-]+$/.test(expression))throw Error();const value=Function(`"use strict";return (${expression})`)();setExpression(Number.isFinite(value)?String(Number(value.toPrecision(12))):'Error');}catch{setExpression('Error');}}
  return <div className={`${s.app} ${theme==='light'?s.light:''} ${collapsed?s.collapsed:''}`}>
    <header className={s.topbar}><div className={s.brand}><img src="/sbooks-brand-badge.png" alt="S-Books" width="46" height="46"/><div><b>S-Books</b><small>{mode==='business'?'Business books: customers, products, estimates, invoices':'Cashflow planner and business books in one local app'}</small></div></div>{mode==='cashflow'&&page==='timeline'&&<label className={s.month}>Jump to month<input type="month" aria-label="Jump to month" value={month} onChange={e=>jump(e.target.value)}/></label>}<div className={s.actions}><span className={s.badge}>Read only</span><button onClick={()=>{const next=theme==='dark'?'light':'dark';setTheme(next);localStorage.setItem('sbooksTheme',next);}}>{theme==='dark'?'Light Mode':'Dark Mode'}</button>{isOwner&&<button onClick={switchMode}>{mode==='business'?'Cashflow Planner':'Business Books'}</button>}<button disabled={busy} onClick={refresh}>Refresh</button><button onClick={signOut}>Sign out</button></div></header>
    <div className={s.layout}><aside className={s.sidebar}><button aria-label="Toggle menu" aria-expanded={!collapsed} title="Toggle menu" onClick={()=>{setCollapsed(!collapsed);localStorage.setItem('sbooksOnlineMenuCollapsed',!collapsed?'1':'0');}}><span className={s.icon}>|||</span><span className={s.navLabel}>{mode==='business'?'Business':'Cashflow'} Menu</span></button><div className={s.sideBrand}><img src="/sbooks-brand-badge.png" alt="" width="42" height="42"/><div className={s.navLabel}><b>S-Books</b><small>{mode==='business'?'Business Books':'Cashflow Planner'}</small></div></div><small className={s.navLabel}>MAIN MENU</small>{(mode==='business'?businessMenu:cashMenu).map(([key,icon,title])=><button key={key} aria-current={page===key?'page':undefined} aria-label={title} title={title} onClick={()=>navigate(key)}><span className={s.icon}>{icon}</span><span className={s.navLabel}>{title}</span></button>)}</aside><main className={s.main}><div className={s.sync}>{syncedAt?`Last synced ${new Date(syncedAt).toLocaleString()}`:'Awaiting first sync'}</div>{error&&<p role="alert">{error}</p>}{busy?<p>Loading books...</p>:mode==='business'?renderBusiness():renderCashflow()}</main></div>
    <button className={s.calcToggle} onClick={()=>setCalc(!calc)}>Calc</button>{calc&&<section className={s.calculator} aria-label="Calculator"><div className={s.toolbar}><b>Calculator</b><button aria-label="Close calculator" onClick={()=>setCalc(false)}>x</button></div><input aria-label="Calculator display" value={expression} onChange={e=>setExpression(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();calculate();}if(e.key==='Escape')setExpression('');}}/><div className={s.calcButtons}>{'789/456*123-0.=+'.split('').map(key=><button key={key} onClick={()=>key==='='?calculate():setExpression(expression==='Error'?key:expression+key)}>{key}</button>)}<button onClick={()=>setExpression('')}>C</button><button onClick={async()=>{try{await navigator.clipboard.writeText(expression);setCalcNotice('Copied');}catch{setCalcNotice('Select the result and press Ctrl+C');}}}>Copy</button></div><small role="status">{calcNotice}</small></section>}
  </div>;
}
